# WOC 4.0
>> ### Machine Learning
>>>> ###### IIT(ISM) Dhanabad
>>>> ###### Arushika

>> ##  Neural on EMNIST Dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as pp
import random as rand

In [ ]:
data = pd.read_csv('emnist-letters-train.csv',header=None)
data = np.array(data)

In [ ]:
data_ = pd.read_csv('emnist-letters-test.csv', header=None) 
data_ = np.array(data_)

In [ ]:
# Seperating Labels and its corresponding values 

# For labels
m,n= data.shape
m_,n_ =data_.shape
y = data[:,0:1]
y_ = data_[:,0:1]
# Seperating x features

X = data[:,1:n]
ones = np.ones([X.shape[0],1]) #This is done because for convinience X_0 is considered to have entering of only 1(for simplicity)
X = np.concatenate ((ones , X) , axis=1)

X_ = data[:,1:n]
ones = np.ones([X_.shape[0],1]) #This is done because for convinience X_0 is considered to have entering of only 1(for simplicity)
X_ = np.concatenate ((ones , X_) , axis=1)

# Setting theta matrice
# Matrice of theta(coefficient of the features in hypothesis function) is supposed to a 1 x (n+1) dimensional matrice
theta = np.zeros([n,26])


In [ ]:
y

array([[23],
       [ 7],
       [16],
       ...,
       [ 1],
       [23],
       [12]])

In [ ]:
#@title Setting Hyperparameters
Alpha = 0.0001 #@param {type:"slider", min:0, max:1, step:0.0000000001}
iters = 1000 #@param {type:"slider", min:100, max:3000, step:100}
alpha_= Alpha
iters_ = iters

In [ ]:
L = np.zeros([m,26])
k =0
for i in y:
    L[k][i-1] = 1
    k += 1

print(L)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
def Sigmoid(z):
    h_x = 1/(1+np.exp(-1*z))
    return h_x

In [ ]:
def Sigmoid_derivative(z):
       return Sigmoid(z) * (1 - Sigmoid(z))


In [ ]:
def params(L_in ,L_out):
    #dimension = L_next*L_current                            
    epsilon = 0.12
    theta=  np.random.rand(L_in,L_out) * 2 * epsilon + (- epsilon )
    return theta

In [ ]:
theta1=params(784,785)
theta2=params(1,785)

In [ ]:
def cost(theta1,theta2,X,Y):         #forward propagation
    m,n=X.shape
    u=np.ones((m,1))
#     X_train=np.concatenate((u,X_train),axis=1)
    a1 = X    #m*n
    z2 = a1@(theta1.T)  #  m,n  @  n,hiddensize
    a2 = Sigmoid(z2) # m x hidden_layer
    a2 = np.concatenate((u,a2),axis=1)   
    z3 = a2@(theta2.T)
    a3 = z3
    h_x = a3
    J=(1/2*m)*np.sum((h_x-Y)**2)
    return J,h_x


In [ ]:
def back_prop(theta1,theta2,X,Y):
    m,n=X.shape
    A1 = X       # m,3
    Z2 = A1@theta1.T   # mx hidden_layer_size == m x 20
    A2 = Sigmoid(Z2)      #  m x hidden_layer_size == m x 20
    
    u=np.ones((m,1))
    A2 = np.concatenate((u,A2),axis=1)   # m x 21
    Z3 = A2@theta2.T     #m x num_labels == m x 26
    A3 = Z3
    h_x = A3                  #m,26
    DELTA3 = A3 - Y
    m,n=(DELTA3@theta2).shape
    DELTA2 = (DELTA3@theta2)*(np.concatenate((np.ones((m,1)),Sigmoid_derivative(Z2)),axis=1))  
    DELTA2 = DELTA2[:,1:]
    theta1_grad = (1/m) * (DELTA2.T @ A1)
    theta2_grad = (1/m) * (DELTA3.T @ A2)
    return theta1_grad,theta2_grad,h_x

In [ ]:
def gradient_descent(theta1,theta2,X,Y):
   for i in range(iters_):
        theta1_grad,theta2_grad,h_x=back_prop(theta1,theta2,X,y)
        theta1=theta1-theta1_grad * alpha_
        theta2=theta2-theta2_grad * alpha_
        j,h_x=cost(theta1,theta2,X,y)
        print(j)
   return theta1, theta2 ,J ,h_x

In [ ]:
theta1_grad = np.zeros(theta1.shape)
theta2_grad = np.zeros(theta2.shape)
back_prop(theta1,theta2,X,y)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


(array([[-0.00365933,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.00042148,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.00139643,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.00291138,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.00239725,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.00138999,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]]),
 array([[-14.02429497,  -2.65817101, -12.50830159, -11.18605037,
          -9.92410636, -10.01082231,  -1.66163122,  -9.43360688,
          -6.54302248,  -3.52611957, -11.59359421,  -1.24750537,
         -11.30457271,  -6.94721771, -13.07532966,  -5.42709921,
          -3.51383958,  -2.91421425,  -5.74705921,  -7.94633129,
          -3.35159942,  -8.40800373,  -8.098374 

In [ ]:
theta1,theta2,h_x=gradient_descent(theta1,theta2,X,y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


951246202322.5233
907345944349.7144
866117770025.8691
827381743677.1118
790968612348.001
756740615487.7137
724562016851.8412
694309001186.4159
665871280492.6598
639147078820.2211
614041179470.0527
590453909870.6902
568288677057.7761
547462024179.2584
527899083131.59454
509522128882.03595
492251971119.3596
476015389813.8015
460749750615.8722
446399541581.4605
432912257990.9181
420236945241.88983
408323156058.77356
397123255030.1708
386593745127.33673
376694349367.7275
367387399467.3169
358637280711.6942
350411602787.2118
342680537675.2516
335414910316.90906
328586534950.15283
322168893069.67725
316137136104.1019
310468185160.18976
305140739006.8646
300134954087.6131
295432056148.5682
291014106485.67706
286863990923.64575
282965284506.15094
279302189805.29926
275859703867.0938
272623758684.29926
269581220093.27924
266719892882.28024
264028586798.5825
261497084953.89008
259115936214.11298
256876204182.4248
254769353418.16675
252787277448.8829
250922335420.17245
249167336093.16745
24751549

In [ ]:
def predict(theta1,theta2,X):
#     X=X/255
    m,n=X.shape
    u=np.ones((m,1))
    a1 = X    #m*n
    z2 = a1@(theta1.T)  #  m,n  @  n,hiddensize
    a2 = Sigmoid(z2) # m x hidden_layer
    a2 = np.concatenate((u,a2),axis=1)   
    z3 = a2@(theta2.T)    
    a3 = z3
    h_x = a3
    return (h_x)
    

In [ ]:
y_pred = predict(theta1 , theta2 ,X_)

In [ ]:
def prediction(matrix):
    
    m,n = matrix.shape
    h = np.zeros((m,1))
    for i in range(m):
        a_sliced = matrix[i]
        index =np.where(a_sliced == np.amax(a_sliced))[0]
#         print((index))
        h[i] = (index+1)
            
    return h

In [ ]:
y_pred2=prediction(y_pred)
y_pred2

In [ ]:
accuracy = np.mean((y_pred2-y_)**2)**0.5
accuracy