In [1]:
import pandas as pd
import numpy as np
import matplotlib as pp
import random as rand

In [15]:
data = pd.read_csv('emnist-letters-train.csv',header=None)
data = np.array(data)

In [16]:
data_ = pd.read_csv('emnist-letters-test.csv', header=None) 
data_ = np.array(data_)

In [17]:
# Seperating Labels and its corresponding values 

# For labels
m,n= data.shape
m_,n_ =data_.shape
y = data[:,0:1]
y_ = data_[:,0:1]
# Seperating x features

X = data[:,1:n]
ones = np.ones([X.shape[0],1]) #This is done because for convinience X_0 is considered to have entering of only 1(for simplicity)
X = np.concatenate ((ones , X) , axis=1)

X_ = data[:,1:n]
ones = np.ones([X_.shape[0],1]) #This is done because for convinience X_0 is considered to have entering of only 1(for simplicity)
X_ = np.concatenate ((ones , X_) , axis=1)

# Setting theta matrice
# Matrice of theta(coefficient of the features in hypothesis function) is supposed to a 1 x (n+1) dimensional matrice
theta = np.zeros([n,26])


In [18]:
y

array([[23],
       [ 7],
       [16],
       ...,
       [ 1],
       [23],
       [12]])

In [19]:
#@title Setting Hyperparameters
Alpha = 0.0001 #@param {type:"slider", min:0, max:1, step:0.0000000001}
iters = 1000 #@param {type:"slider", min:100, max:3000, step:100}
alpha_= Alpha
iters_ = iters

In [20]:
L = np.zeros([m,26])
k =0
for i in y:
    L[k][i-1] = 1
    k += 1

print(L)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
def Sigmoid(z):
    h_x = 1/(1+np.exp(-1*z))
    return h_x

In [22]:
def Sigmoid_derivative(z):
       return Sigmoid(z) * (1 - Sigmoid(z))


In [23]:
def params(L_in ,L_out):
    #dimension = L_next*L_current                            
    epsilon = 0.12
    theta=  np.random.rand(L_in,L_out) * 2 * epsilon + (- epsilon )
    return theta

In [30]:
theta1=params(784,785)
theta2=params(1,785)

In [25]:
def cost(theta1,theta2,X,Y):         #forward propagation
    m,n=X.shape
    u=np.ones((m,1))
#     X_train=np.concatenate((u,X_train),axis=1)
    a1 = X    #m*n
    z2 = a1@(theta1.T)  #  m,n  @  n,hiddensize
    a2 = Sigmoid(z2) # m x hidden_layer
    a2 = np.concatenate((u,a2),axis=1)   
    z3 = a2@(theta2.T)
    a3 = z3
    h_x = a3
    J=(1/2*m)*np.sum((h_x-Y)**2)
    return J,h_x


In [26]:
def back_prop(theta1,theta2,X,Y):
    m,n=X.shape
    A1 = X       # m,3
    Z2 = A1@theta1.T   # mx hidden_layer_size == m x 20
    A2 = Sigmoid(Z2)      #  m x hidden_layer_size == m x 20
    
    u=np.ones((m,1))
    A2 = np.concatenate((u,A2),axis=1)   # m x 21
    Z3 = A2@theta2.T     #m x num_labels == m x 26
    A3 = Z3
    h_x = A3                  #m,26
    DELTA3 = A3 - Y
    m,n=(DELTA3@theta2).shape
    DELTA2 = (DELTA3@theta2)*(np.concatenate((np.ones((m,1)),Sigmoid_derivative(Z2)),axis=1))  
    DELTA2 = DELTA2[:,1:]
    theta1_grad = (1/m) * (DELTA2.T @ A1)
    theta2_grad = (1/m) * (DELTA3.T @ A2)
    return theta1_grad,theta2_grad,h_x

In [27]:
def gradient_descent(theta1,theta2,X,Y):
   for i in range(iters_):
        theta1_grad,theta2_grad,h_x=back_prop(theta1,theta2,X,y)
        theta1=theta1-theta1_grad * alpha_
        theta2=theta2-theta2_grad * alpha_
        j,h_x=cost(theta1,theta2,X,y)
        print(j)
   return theta1, theta2 ,J ,h_x

In [31]:
theta1_grad = np.zeros(theta1.shape)
theta2_grad = np.zeros(theta2.shape)
back_prop(theta1,theta2,X,y)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


(array([[-0.00034202,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.00109121,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [-0.00038967,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.00046849,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.00164168,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.00136158,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]]),
 array([[-12.99412962,  -6.0516089 ,  -2.78048863,  -5.35484177,
          -7.02531969,  -6.2808382 ,  -4.5794754 ,  -8.93378945,
          -7.18564591,  -1.34083399,  -2.44905611,  -7.09881182,
          -9.95238031, -10.93378624,  -8.31160827,  -2.71279408,
         -11.30671381,  -1.37152982,  -1.88669267,  -9.18184534,
          -4.78879065,  -3.33832779,  -2.0966023

In [ ]:
theta1,theta2,h_x=gradient_descent(theta1,theta2,X,y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


845197387025.331
807312824527.8947
771731803292.5635
738299094985.8147
706869914378.9268
677330821781.1821
649577065841.8474
623505608510.4878
599011608242.902
575990186952.0918
554349982561.157
534013352604.94855
514905840144.01135
496952023629.2275
480076625807.2943
464210307598.5659
449294784250.6726
435279571578.92786
422115951187.3594
409753933026.4643
398142796611.4371
387233432501.3817
376981967442.1131
367349287105.79285
358299513539.9585
349798526204.87585
341813509667.7565
334313813459.2006
327270424178.4877
320655576308.84265
314443190444.3727
308608973838.54926
303129785848.72644
297983414424.7881
293149045375.48047
288607516278.2312
284341165554.3602
280333506221.1913
276568884451.9779
273032416909.19446
269710160073.40894
266589204209.44455
263657598323.08133
260904094547.98593
258317886701.02936
255888542984.11765
253606177708.8878
251461601749.4922
249446257984.59235
247552086905.17496
245771476440.65738
244097257267.48035


In [ ]:
def predict(theta1,theta2,X):
#     X=X/255
    m,n=X.shape
    u=np.ones((m,1))
    a1 = X    #m*n
    z2 = a1@(theta1.T)  #  m,n  @  n,hiddensize
    a2 = Sigmoid(z2) # m x hidden_layer
    a2 = np.concatenate((u,a2),axis=1)   
    z3 = a2@(theta2.T)    
    a3 = z3
    h_x = a3
    return (h_x)
    

In [ ]:
y_pred = predict(theta1 , theta2 ,X_)

In [ ]:
def prediction(matrix):
    
    m,n = matrix.shape
    h = np.zeros((m,1))
    for i in range(m):
        a_sliced = matrix[i]
        index =np.where(a_sliced == np.amax(a_sliced))[0]
#         print((index))
        h[i] = (index+1)
            
    return h

In [ ]:
y_pred2=prediction(y_pred)
y_pred2

In [ ]:
accuracy = np.mean((y_pred2-y_)**2)**0.5
accuracy